import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navBar/navBar";
import Footer from "@/components/footer/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="apple-touch-icon" href="/account/checkout/plantImg.png" />
        <link rel="icon" href="/account/checkout/plantImg.png" sizes="any" />
        <link rel="icon" href="/account/checkout/plantImg.png" type="image/svg+xml" /> */}
        </head>
      <body
      //   className={`${geistSans.variable} ${geistMono.variable} antialiased`
      // }
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
